config/routes.rb
Rails.application.routes.draw do
  resources :pages
  get 'channel/:channel_id/library', to: 'channels#library', as: :library
  resources :library_items
  resources :library_folders
  get 'course_items/category'
  resources :course_items
  resources :question_comments do
    resource :question_comment_votes, only: :show
  end
  resources :questions
  resources :lesson_comments
  resources :lessons
  resources :community_comments do
    resource :community_comment_votes, only: :show
  end
  resources :article_comments do
    resource :article_comment_votes, only: :show
  end
  resources :video_comments do
    resource :video_comment_votes, only: :show
  end
  get 'dashboard/index'
  get 'communities/list'
  resources :communities
  get 'courses/info'
  get 'courses/list'
  resources :courses
  resources :webhooks, only: [:create]
  get 'articles/list'
  resources :articles
  get 'videos/list'
  resources :videos
  resources :channels
  get 'account_affiliations/info'
  get 'account_affiliations/become_admin'
  resources :account_affiliations
  get 'accounts/switch'
  get 'accounts/select'
  get 'accounts/manage'
  get 'accounts/user_info'
  get 'accounts/new_affiliation'
  get 'accounts/members'
  get 'accounts/confirmed'
  get 'accounts/:id/configuration', to: 'accounts#configuration', as: :account_configuration
  resources :accounts do
    collection do
      post :search
    end
  end
  devise_for :users
  get 'home/index'
  root to: "home#index"
end

app/models/community_comment.rb
class CommunityComment < ApplicationRecord
  include ActionView::RecordIdentifier
  belongs_to :user
  belongs_to :community

  has_many :community_comment_votes, dependent: :destroy

  has_rich_text :content

  after_create_commit do
    community = Community.find(self.community_id)
    broadcast_append_to :community_comments, target: "comments_#{dom_id(community)}", partial: "community_comments/community_comment", locals: { community_comment: self }
  end
  
  def community_comment_vote_count
    community_comment_votes.sum(:choice)
  end
end

app/controllers/community_comments_controller.rb
class CommunityCommentsController < ApplicationController
  before_action :set_community_comment, only: %i[ show edit update destroy ]

  # GET /community_comments or /community_comments.json
  def index
    @community = Community.friendly.find(params[:id])
    @community_comments = CommunityComment.where(community_id: @community.id)
  end

  # GET /community_comments/1 or /community_comments/1.json
  def show
  end

  # GET /community_comments/new
  def new
    @community_comment = current_user.community_comments.new
  end

  # GET /community_comments/1/edit
  def edit
  end

  # POST /community_comments or /community_comments.json
  def create
    @community_comment = current_user.community_comments.new(community_comment_params)
    @community = Community.friendly.find(@community_comment.community_id)
    
    respond_to do |format|
      if @community_comment.save
        format.turbo_stream {
          render turbo_stream: turbo_stream.replace(
            "new_community_comment",
            partial: "community_comments/form",
            locals: { community_comment: current_user.community_comments.new, community_id: @community_comment.community_id }
          )
        }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @community_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /community_comments/1 or /community_comments/1.json
  def update
    respond_to do |format|
      if @community_comment.update(community_comment_params)
        format.html { redirect_to community_comment_url(@community_comment), notice: "Community comment was successfully updated." }
        format.json { render :show, status: :ok, location: @community_comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @community_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /community_comments/1 or /community_comments/1.json
  def destroy
    @community_comment.destroy

    respond_to do |format|
      format.html { redirect_to community_comments_url, notice: "Community comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_community_comment
      @community_comment = CommunityComment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def community_comment_params
      params.require(:community_comment).permit(:user_id, :community_id, :content)
    end
end

app/helpers/community_comments_helper.rb
module CommunityCommentsHelper
end

app/views/community_comments/_community_comment.html.erb
<div id="<%= dom_id community_comment %>">
  <div>
    <h5><%= community_comment.user.name %></h5>
    <p><%= community_comment.content %></p>
    <p><%= community_comment.community_comment_vote_count %></p>
    <%= link_to "Up vote", community_comment_community_comment_votes_path(community_comment, choice: :up_vote, format: :trubo_stream) %>
    <%= link_to "Down vote", community_comment_community_comment_votes_path(community_comment, choice: :down_vote, format: :trubo_stream) %>
  </div>
</div>

app/views/community_comments/_form.html.erb
<%= turbo_frame_tag "new_community_comment", target: :_top do %>
  <%= form_with(model: community_comment, class: "contents") do |form| %>
    
    <%= form.hidden_field :community_id, value: community_id %>

      <div class="my-5">
        <%= form.rich_text_area :content, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
      </div>

    <div class="inline">
      <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
    </div>
  <% end %>
<% end %>

app/views/community_comments/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing community comment</h1>

  <%= render "form", community_comment: @community_comment %>

  <%= link_to "Show this community comment", @community_comment, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to community comments", community_comments_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/community_comments/index.html.erb
<div class="w-full">
<%= turbo_frame_tag "comments_module" do %>
  <div id="comments_<%= dom_id @community %>" class="min-w-full">
    <%= render @community_comments %>
  </div>
  <%= turbo_frame_tag "new_community_comment", src: new_community_comment_path(community_id: @community.id) %>
<% end %>
</div>

app/views/community_comments/new.html.erb
<%= render "form", community_comment: @community_comment, community_id: params[:community_id] %>

app/views/community_comments/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @community_comment %>

    <%= link_to 'Edit this community_comment', edit_community_comment_path(@community_comment), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this community_comment', community_comment_path(@community_comment), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to community_comments', community_comments_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>