config/routes.rb
Rails.application.routes.draw do
  resources :pages
  get 'channel/:channel_id/library', to: 'channels#library', as: :library
  resources :library_items
  resources :library_folders
  get 'course_items/category'
  resources :course_items
  resources :question_comments do
    resource :question_comment_votes, only: :show
  end
  resources :questions
  resources :lesson_comments
  resources :lessons
  resources :community_comments do
    resource :community_comment_votes, only: :show
  end
  resources :article_comments do
    resource :article_comment_votes, only: :show
  end
  resources :video_comments do
    resource :video_comment_votes, only: :show
  end
  get 'dashboard/index'
  get 'communities/list'
  resources :communities
  get 'courses/info'
  get 'courses/list'
  resources :courses
  resources :webhooks, only: [:create]
  get 'articles/list'
  resources :articles
  get 'videos/list'
  resources :videos
  resources :channels
  get 'account_affiliations/info'
  get 'account_affiliations/become_admin'
  resources :account_affiliations
  get 'accounts/switch'
  get 'accounts/select'
  get 'accounts/manage'
  get 'accounts/user_info'
  get 'accounts/new_affiliation'
  get 'accounts/members'
  get 'accounts/confirmed'
  get 'accounts/:id/configuration', to: 'accounts#configuration', as: :account_configuration
  resources :accounts do
    collection do
      post :search
    end
  end
  devise_for :users
  get 'home/index'
  root to: "home#index"
end

app/models/article.rb
class Article < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  has_rich_text :content
  
  belongs_to :channel

  validates :title, presence: true
  has_one_attached :thumbnail

  enum privacy: [:draft, :course, :open]
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  def list
    @menu_articles = true
    @articles = Article.where(channel_id: current_channel.id)
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)
    @article.channel_id = current_channel.id

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:channel_id, :title, :score, :content, :thumbnail, :privacy)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Channel:</strong>
    <%= article.channel_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= article.title %>
  </p>

  <p class="my-5">
    <%= article.content %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this article", article, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this article', edit_article_path(article), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/articles/_form.html.erb
<main class="py-6 bg-gray-100 h-screen">
  <%= form_with(model: article, class: "contents") do |form| %>
  
    <div class="max-w-3xl mx-auto px-4 sm:px-6 md:flex md:items-center md:justify-between md:space-x-5 lg:max-w-7xl lg:px-8">
      <div class="flex items-center space-x-5">
        <div>
          <h1 class="font-bold text-2xl"><%= t('.article') %></h1>
        </div>
      </div>
      <div class="mt-6 flex flex-col-reverse justify-stretch space-y-4 space-y-reverse sm:flex-row-reverse sm:justify-end sm:space-x-reverse sm:space-y-0 sm:space-x-3 md:mt-0 md:flex-row md:space-x-3">
        <%= form.submit t('.save_article'), class: "inline-flex items-center justify-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-100 focus:ring-blue-500 cursor-pointer" %>
      </div>
    </div>
  
    <% if article.errors.any? %>
      <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
        <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

        <ul>
          <% article.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mt-6 max-w-3xl mx-auto grid grid-cols-1 gap-6 sm:px-6 lg:max-w-7xl lg:grid-flow-col-dense lg:grid-cols-3">
      <div class="space-y-6 lg:col-start-1 lg:col-span-2">
        <div class="bg-white shadow sm:rounded-lg sm:overflow-hidden px-4 py-5 sm:px-6">
          <div class="my-5">
            <span class="font-bold"><%= t('.title') %></span>
            <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
          </div>
          <div class="field article-field mb-8">
            <%= form.rich_text_area :content %>
          </div>
        </div>
      </div>
    
      <div class="space-y-6 lg:col-start-3 lg:col-span-1">
        <div class="bg-white px-4 py-5 shadow sm:rounded-lg sm:px-6">
          <div class="font-bold mb-1"><%= t('.privacy') %></div>
          <div class="flex">
            <div>
              <div class="form-check">
                <%= form.radio_button :privacy, :draft, class: "form-check-input appearance-none rounded-full h-4 w-4 border border-gray-300 bg-white checked:bg-blue-600 checked:border-blue-600 focus:outline-none transition duration-200 mt-1 align-top bg-no-repeat bg-center bg-contain float-left mr-2 cursor-pointer" %>
                <%= form.label :privacy, t('.private'), value: :draft, class: "form-check-label inline-block text-gray-800" %>
              </div>
              <div class="form-check">
                <%= form.radio_button :privacy, :course, class: "form-check-input appearance-none rounded-full h-4 w-4 border border-gray-300 bg-white checked:bg-blue-600 checked:border-blue-600 focus:outline-none transition duration-200 mt-1 align-top bg-no-repeat bg-center bg-contain float-left mr-2 cursor-pointer" %>
                <%= form.label :privacy, t('.only_courses'), value: :course, class: "form-check-label inline-block text-gray-800" %>
              </div>
              <div class="form-check">
                <%= form.radio_button :privacy, :open, checked: true, class: "form-check-input appearance-none rounded-full h-4 w-4 border border-gray-300 bg-white checked:bg-blue-600 checked:border-blue-600 focus:outline-none transition duration-200 mt-1 align-top bg-no-repeat bg-center bg-contain float-left mr-2 cursor-pointer" %>
                <%= form.label :privacy, t('.public'), value: :open, class: "form-check-label inline-block text-gray-800" %>
              </div>
            </div>
          </div>
          <div class="my-5" data-controller='image-upload'>
            <div class="font-bold mb-1"><%= t('.thumbnail') %></div>
            <%= form.file_field :thumbnail, 'data-image-upload-target': 'input', 'data-action': 'image-upload#changed' %>
            <div class="mt-2">
              <% if @article.thumbnail.attached? %>
                <div class="overflow-hidden">
                  <%= image_tag @article.thumbnail.variant(resize_to_limit: [250, 200]),
                  'data-image-upload-target': 'image', class: "rounded-lg" if @article.thumbnail.attached? %>
                </div>
              <% else %>
                <div class="border rounded-lg bg-gray-200 overflow-hidden" style="width: 250px; height: 200px;">
                  <%= content_tag :img, nil, src: nil, 'data-image-upload-target': 'image' %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
        
    </div>
  <% end %>
</main>

app/views/articles/edit.html.erb
<%= render ("layouts/dashboard") %>
  
  <div class="max-w-7xl mx-auto px-4 sm:px-6">
    <div class="border-t border-gray-200 py-3">
      <nav class="flex" aria-label="Breadcrumb">
        
        <div class="hidden sm:block">
          <ol role="list" class="flex items-center space-x-4">
            <li>
              <div>
                <%= link_to dashboard_index_path, class: "text-gray-400 hover:text-gray-500" do %>
                  <svg class="flex-shrink-0 h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                    <path d="M10.707 2.293a1 1 0 00-1.414 0l-7 7a1 1 0 001.414 1.414L4 10.414V17a1 1 0 001 1h2a1 1 0 001-1v-2a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 001 1h2a1 1 0 001-1v-6.586l.293.293a1 1 0 001.414-1.414l-7-7z" />
                  </svg>
                  <span class="sr-only">Home</span>
                <% end %>
              </div>
            </li>

            <li>
              <div class="flex items-center">
                <svg class="flex-shrink-0 h-5 w-5 text-gray-300" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20" aria-hidden="true">
                  <path d="M5.555 17.776l8-16 .894.448-8 16-.894-.448z" />
                </svg>
                <%= link_to t('.articles'), articles_list_path, class: "ml-4 text-sm font-medium text-gray-500 hover:text-gray-700" %>
              </div>
            </li>

            <li>
              <div class="flex items-center">
                <svg class="flex-shrink-0 h-5 w-5 text-gray-300" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20" aria-hidden="true">
                  <path d="M5.555 17.776l8-16 .894.448-8 16-.894-.448z" />
                </svg>
                <span class="ml-4 text-sm font-medium text-gray-500"><%= t('.edit_article') %></span>
              </div>
            </li>

          </ol>
        </div>
      </nav>
    </div>
  </div>

  <%= render "form", article: @article %>
  
</div>

app/views/articles/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Articles</h1>
    <%= link_to 'New article', new_article_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="articles" class="min-w-full">
    <%= render @articles %>
  </div>
</div>

app/views/articles/list.html.erb
<%= render ("layouts/dashboard") %>
  
  <div class="py-6">
    <div class="max-w-3xl mx-auto sm:px-6 lg:max-w-7xl lg:grid lg:grid-cols-12 lg:gap-8">
      <div class="hidden lg:block lg:col-span-3">
        <%= render ("layouts/dashboard_menu") %>
      </div>
      <main class="lg:col-span-9">
        <div class="flex items-center space-x-5">
          <div>
            <h1 class="font-bold text-2xl"><%= t('.title_articles') %></h1>
          </div>
        </div>
        <div class="mt-6 flex flex-col-reverse justify-stretch space-y-4 space-y-reverse sm:flex-row-reverse sm:justify-end sm:space-x-reverse sm:space-y-0 sm:space-x-3 md:mt-0 md:flex-row md:space-x-3">
          <%= link_to t('.new_article'), new_article_path, class: "inline-flex items-center justify-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-100 focus:ring-blue-500 cursor-pointer" %>
        </div>

        <% @articles.each do |article| %>
          <div class="border-b py-4">
            <%= link_to article.title, edit_article_path(article), class: "hover:text-gray-600" %>
          </div>
        <% end %>
      </main>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<%= render ("layouts/dashboard") %>
  
  <div class="max-w-7xl mx-auto px-4 sm:px-6">
    <div class="border-t border-gray-200 py-3">
      <nav class="flex" aria-label="Breadcrumb">
        
        <div class="hidden sm:block">
          <ol role="list" class="flex items-center space-x-4">
            <li>
              <div>
                <%= link_to dashboard_index_path, class: "text-gray-400 hover:text-gray-500" do %>
                  <svg class="flex-shrink-0 h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                    <path d="M10.707 2.293a1 1 0 00-1.414 0l-7 7a1 1 0 001.414 1.414L4 10.414V17a1 1 0 001 1h2a1 1 0 001-1v-2a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 001 1h2a1 1 0 001-1v-6.586l.293.293a1 1 0 001.414-1.414l-7-7z" />
                  </svg>
                  <span class="sr-only">Home</span>
                <% end %>
              </div>
            </li>

            <li>
              <div class="flex items-center">
                <svg class="flex-shrink-0 h-5 w-5 text-gray-300" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20" aria-hidden="true">
                  <path d="M5.555 17.776l8-16 .894.448-8 16-.894-.448z" />
                </svg>
                <%= link_to t('.articles'), articles_list_path, class: "ml-4 text-sm font-medium text-gray-500 hover:text-gray-700" %>
              </div>
            </li>

            <li>
              <div class="flex items-center">
                <svg class="flex-shrink-0 h-5 w-5 text-gray-300" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20" aria-hidden="true">
                  <path d="M5.555 17.776l8-16 .894.448-8 16-.894-.448z" />
                </svg>
                <span class="ml-4 text-sm font-medium text-gray-500"><%= t('.new_article') %></span>
              </div>
            </li>

          </ol>
        </div>
      </nav>
    </div>
  </div>
  
  <%= render "form", article: @article %>
  
</div>

app/views/articles/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @article %>

    <%= link_to 'Edit this article', edit_article_path(@article), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this article', article_path(@article), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to articles', articles_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  
    <%= turbo_stream_from :article_comments %>
    <%= turbo_frame_tag "comments_module", src: article_comments_path(id: params[:id]) %>
  </div>
</div>