config/routes.rb
Rails.application.routes.draw do
  resources :pages
  get 'channel/:channel_id/library', to: 'channels#library', as: :library
  resources :library_items
  resources :library_folders
  get 'course_items/category'
  resources :course_items
  resources :question_comments do
    resource :question_comment_votes, only: :show
  end
  resources :questions
  resources :lesson_comments
  resources :lessons
  resources :community_comments do
    resource :community_comment_votes, only: :show
  end
  resources :article_comments do
    resource :article_comment_votes, only: :show
  end
  resources :video_comments do
    resource :video_comment_votes, only: :show
  end
  get 'dashboard/index'
  get 'communities/list'
  resources :communities
  get 'courses/info'
  get 'courses/list'
  resources :courses
  resources :webhooks, only: [:create]
  get 'articles/list'
  resources :articles
  get 'videos/list'
  resources :videos
  resources :channels
  get 'account_affiliations/info'
  get 'account_affiliations/become_admin'
  resources :account_affiliations
  get 'accounts/switch'
  get 'accounts/select'
  get 'accounts/manage'
  get 'accounts/user_info'
  get 'accounts/new_affiliation'
  get 'accounts/members'
  get 'accounts/confirmed'
  get 'accounts/:id/configuration', to: 'accounts#configuration', as: :account_configuration
  resources :accounts do
    collection do
      post :search
    end
  end
  devise_for :users
  get 'home/index'
  root to: "home#index"
end

app/models/video.rb
class Video < ApplicationRecord
  extend FriendlyId
  friendly_id :publicid, use: :slugged
  
  belongs_to :channel
  validates :title, presence: true
  has_one_attached :file
  has_one_attached :thumbnail
  has_many :video_comments, dependent: :destroy
  has_rich_text :description

  enum privacy: [:draft, :course, :open]
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ list new edit create update destroy ]

  # GET /videos or /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1 or /videos/1.json
  def show
  end

  def list
    @menu_videos = true
    @videos = Video.where(channel_id: current_channel.id)
  end

  # GET /videos/new
  def new
    @menu_videos = true
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
    @menu_videos = true
  end

  # POST /videos or /videos.json
  def create
    @video = Video.new(video_params)
    @video.channel_id = current_channel.id

    respond_to do |format|
      if @video.save
        create_mux_video(@video)
        format.html { redirect_to edit_video_path(@video) }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_mux_video(video)
    assets_api = MuxRuby::AssetsApi.new
    create_asset = MuxRuby::CreateAssetRequest.new
    create_asset.input = url_for(video.file)
    puts "MUX URL: #{create_asset.input}"
    create_asset.playback_policy = [MuxRuby::PlaybackPolicy::PUBLIC]
    create_response = assets_api.create_asset(create_asset)  
    puts "MUX response playback id: #{create_response.data.playback_ids.first.id}"
    video.playback_id = create_response.data.playback_ids.first.id
    video.policy = create_response.data.playback_ids.first.policy
    video.mux_asset_id = create_response.data.id
    video.save
  end

  # PATCH/PUT /videos/1 or /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to video_url(@video), notice: "Video was successfully updated." }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1 or /videos/1.json
  def destroy
    @video.destroy

    respond_to do |format|
      format.html { redirect_to videos_url, notice: "Video was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def video_params
      params.require(:video).permit(:channel_id, :title, :description, :score, :visible, :privacy, :publicid, :playback_id, :policy, :mux_asset_id, :status, :max_stored_resolution, :max_stored_frame_rate, :duration, :aspect_ratio, :file, :thumbnail)
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_with(model: video, class: "contents") do |form| %>
  <% if video.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
        <% video.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :publicid, value: SecureRandom.base58(10) %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div data-controller="upload" class="my-5">
    <%= form.file_field :file, direct_upload: true,
      data: { upload_target: 'input', action: "change->upload#uploadFile" } %>
    <div data-upload-target="progress"></div>
    <div data-upload-target="saveButton" class="hidden mt-4">
      <%= form.submit t('.save_video'), class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
    </div >
  </div>

<% end %>

app/views/videos/_thumbnail.html.erb
<li class="relative">
  <div class="group block w-full aspect-w-16 aspect-h-9 rounded-lg bg-gray-100 focus-within:ring-2 focus-within:ring-offset-2 focus-within:ring-offset-gray-100 focus-within:ring-indigo-500 overflow-hidden">
    <img src="https://images.unsplash.com/photo-1492724724894-7464c27d0ceb?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&amp;ixlib=rb-1.2.1&amp;auto=format&amp;fit=crop&amp;w=512&amp;q=80" alt="" class="object-cover pointer-events-none group-hover:opacity-75" class="w-36">
  </div>
  <p><%= video.title %></p>
</li>

app/views/videos/_video.html.erb
<div id="<%= dom_id video %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Channel:</strong>
    <%= video.channel_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= video.title %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Score:</strong>
    <%= video.score %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Visible:</strong>
    <%= video.visible %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Publicid:</strong>
    <%= video.publicid %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Playback:</strong>
    <%= video.playback_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Policy:</strong>
    <%= video.policy %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Mux asset:</strong>
    <%= video.mux_asset_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Status:</strong>
    <%= video.status %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Max stored resolution:</strong>
    <%= video.max_stored_resolution %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Max stored frame rate:</strong>
    <%= video.max_stored_frame_rate %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Duration:</strong>
    <%= video.duration %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Aspect ratio:</strong>
    <%= video.aspect_ratio %>
  </p>

  <p class="my-5">
    <strong>Video:</strong>
    <div class="h-auto">
      <video
  id="mux-default"
  class="video-js vjs-16-9"
  controls
  preload="auto"
  width="100%"
  poster="https://image.mux.com/DS00Spx1CV902MCtPj5WknGlR102V5HFkDe/thumbnail.jpg"
  data-setup='{
    "timelineHoverPreviews": true,
    "plugins": {
      "mux": {
        "data": {
          "env_key": "ENV_KEY",
          "video_title": "My Great Video"
        }
      }
    }
  }'
>
  <source src="<%= video.playback_id %>" type="video/mux" />
</video>
    </div>
  </p>


  <% if action_name != "show" %>
    <%= link_to "Show this video", video, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this video', edit_video_path(video), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/videos/edit.html.erb
<%= render ("layouts/dashboard") %>
  
  <div class="max-w-7xl mx-auto px-4 sm:px-6">
    <div class="border-t border-gray-200 py-3">
      <nav class="flex" aria-label="Breadcrumb">
        
        <div class="hidden sm:block">
          <ol role="list" class="flex items-center space-x-4">
            <li>
              <div>
                <%= link_to dashboard_index_path, class: "text-gray-400 hover:text-gray-500" do %>
                  <svg class="flex-shrink-0 h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                    <path d="M10.707 2.293a1 1 0 00-1.414 0l-7 7a1 1 0 001.414 1.414L4 10.414V17a1 1 0 001 1h2a1 1 0 001-1v-2a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 001 1h2a1 1 0 001-1v-6.586l.293.293a1 1 0 001.414-1.414l-7-7z" />
                  </svg>
                  <span class="sr-only">Home</span>
                <% end %>
              </div>
            </li>

            <li>
              <div class="flex items-center">
                <svg class="flex-shrink-0 h-5 w-5 text-gray-300" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20" aria-hidden="true">
                  <path d="M5.555 17.776l8-16 .894.448-8 16-.894-.448z" />
                </svg>
                <%= link_to t('.videos'), videos_list_path, class: "ml-4 text-sm font-medium text-gray-500 hover:text-gray-700" %>
              </div>
            </li>

            <li>
              <div class="flex items-center">
                <svg class="flex-shrink-0 h-5 w-5 text-gray-300" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20" aria-hidden="true">
                  <path d="M5.555 17.776l8-16 .894.448-8 16-.894-.448z" />
                </svg>
                <span class="ml-4 text-sm font-medium text-gray-500"><%= t('.video_details') %></span>
              </div>
            </li>

          </ol>
        </div>
      </nav>
    </div>
  </div>
  

  <main class="py-6 bg-gray-100 h-screen">
    <%= form_with(model: @video, class: "contents") do |form| %>

      <div class="max-w-3xl mx-auto px-4 sm:px-6 md:flex md:items-center md:justify-between md:space-x-5 lg:max-w-7xl lg:px-8">
        <div class="flex items-center space-x-5">
          <div>
            <h1 class="font-bold text-2xl"><%= t('.video_details') %></h1>
          </div>
        </div>
        <div class="mt-6 flex flex-col-reverse justify-stretch space-y-4 space-y-reverse sm:flex-row-reverse sm:justify-end sm:space-x-reverse sm:space-y-0 sm:space-x-3 md:mt-0 md:flex-row md:space-x-3">
          <%= form.submit t('.save_video'), class: "inline-flex items-center justify-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-100 focus:ring-blue-500 cursor-pointer" %>
        </div>
      </div>
  
    
      <% if @video.errors.any? %>
        <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
          <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

          <ul>
            <% @video.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      
      <div class="mt-6 max-w-3xl mx-auto grid grid-cols-1 gap-6 sm:px-6 lg:max-w-7xl lg:grid-flow-col-dense lg:grid-cols-3">
        <div class="space-y-6 lg:col-start-1 lg:col-span-2">
          
          <section aria-labelledby="video-info">
            <div class="bg-white shadow sm:rounded-lg sm:overflow-hidden px-4 py-5 sm:px-6">
              <div>
                <span class="font-bold"><%= t('.title') %></span>
                <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
              </div>

              <div class="my-5" data-controller='image-upload'>
                <div class="font-bold mb-1"><%= t('.thumbnail') %></div>
                <%= form.file_field :thumbnail, 'data-image-upload-target': 'input', 'data-action': 'image-upload#changed' %>
                <div class="mt-2">
                  <% if @video.thumbnail.attached? %>
                    <div class="overflow-hidden">
                      <%= image_tag @video.thumbnail.variant(resize_to_limit: [250, 141]),
                      'data-image-upload-target': 'image', class: "rounded-lg" if @video.thumbnail.attached? %>
                    </div>
                  <% else %>
                    <div class="border rounded-lg bg-gray-200 overflow-hidden" style="width: 250px; height: 141px;">
                      <%= content_tag :img, nil, src: nil, 'data-image-upload-target': 'image' %>
                    </div>
                  <% end %>
                </div>
              </div>

              <div class="my-5">
                <div class="mb-2">
                  <span class="font-bold"><%= t('.description') %></span>
                </div>
                <%= form.rich_text_area :description %>
              </div>
            </div>
          </section>

          
        </div>

        <section aria-labelledby="options" class="lg:col-start-3 lg:col-span-1">
          <div class="bg-white px-4 py-5 shadow sm:rounded-lg sm:px-6">
            <div class="font-bold mb-1"><%= t('.privacy') %></div>
              <div class="flex">
                <div>
                  <div class="form-check">
                    <%= form.radio_button :privacy, :draft, class: "form-check-input appearance-none rounded-full h-4 w-4 border border-gray-300 bg-white checked:bg-blue-600 checked:border-blue-600 focus:outline-none transition duration-200 mt-1 align-top bg-no-repeat bg-center bg-contain float-left mr-2 cursor-pointer" %>
                    <%= form.label :privacy, "Privado", value: :draft, class: "form-check-label inline-block text-gray-800" %>
                  </div>
                  <div class="form-check">
                    <%= form.radio_button :privacy, :course, class: "form-check-input appearance-none rounded-full h-4 w-4 border border-gray-300 bg-white checked:bg-blue-600 checked:border-blue-600 focus:outline-none transition duration-200 mt-1 align-top bg-no-repeat bg-center bg-contain float-left mr-2 cursor-pointer" %>
                    <%= form.label :privacy, "Sólo en cursos", value: :course, class: "form-check-label inline-block text-gray-800" %>
                  </div>
                  <div class="form-check">
                    <%= form.radio_button :privacy, :open, checked: true, class: "form-check-input appearance-none rounded-full h-4 w-4 border border-gray-300 bg-white checked:bg-blue-600 checked:border-blue-600 focus:outline-none transition duration-200 mt-1 align-top bg-no-repeat bg-center bg-contain float-left mr-2 cursor-pointer" %>
                    <%= form.label :privacy, "Público", value: :open, class: "form-check-label inline-block text-gray-800" %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

    <% end %>
  </main>
</div>

app/views/videos/index.html.erb
<div class="h-screen flex overflow-hidden bg-white">
  
  <%= render ("layouts/mobile_navigation") %>
  <%= render ("layouts/desktop_navigation") %>
  
  <div class="flex flex-col w-0 flex-1 overflow-hidden">
    <%= render ("layouts/top_bar") %>

    <main class="flex-1 relative overflow-y-auto focus:outline-none" tabindex="-1">
      <div class="bg-gray-100">
        <div class="max-w-7xl mx-auto py-8 px-4 sm:px-6 lg:px-8">
          <ul class="grid grid-cols-2 gap-x-4 gap-y-8 sm:grid-cols-3 sm:gap-x-6 lg:grid-cols-4 xl:gap-x-8">
          <% @videos.each do |video| %>
            <%= render partial: "thumbnail", locals: {video: video} %>
          <% end %>
          </ul>
        </div>
      </div>
    </main>
  </div>
</div>

app/views/videos/list.html.erb
<%= render ("layouts/dashboard") %>
  
  <div class="py-6">
    <div class="max-w-3xl mx-auto sm:px-6 lg:max-w-7xl lg:grid lg:grid-cols-12 lg:gap-8">
      <div class="hidden lg:block lg:col-span-3">
        <%= render ("layouts/dashboard_menu") %>
      </div>
      <main class="lg:col-span-9">
        <div class="flex items-center space-x-5">
          <div>
            <h1 class="font-bold text-2xl"><%= t('.title_videos') %></h1>
          </div>
        </div>
        <div class="mt-6 flex flex-col-reverse justify-stretch space-y-4 space-y-reverse sm:flex-row-reverse sm:justify-end sm:space-x-reverse sm:space-y-0 sm:space-x-3 md:mt-0 md:flex-row md:space-x-3">
          <%= link_to t('.new_video'), new_video_path, class: "inline-flex items-center justify-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-100 focus:ring-blue-500 cursor-pointer" %>
        </div>

        <% @videos.each do |video| %>
          <div class="border-b py-4">
            <%= link_to video.title, edit_video_path(video), class: "hover:text-gray-600" %>
          </div>
        <% end %>
      </main>
    </div>
  </div>
</div>
    

app/views/videos/new.html.erb
<%= render ("layouts/dashboard") %>
  
  <div class="max-w-7xl mx-auto px-4 sm:px-6">
    <div class="border-t border-gray-200 py-3">
      <nav class="flex" aria-label="Breadcrumb">
        
        <div class="hidden sm:block">
          <ol role="list" class="flex items-center space-x-4">
            <li>
              <div>
                <%= link_to dashboard_index_path, class: "text-gray-400 hover:text-gray-500" do %>
                  <svg class="flex-shrink-0 h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                    <path d="M10.707 2.293a1 1 0 00-1.414 0l-7 7a1 1 0 001.414 1.414L4 10.414V17a1 1 0 001 1h2a1 1 0 001-1v-2a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 001 1h2a1 1 0 001-1v-6.586l.293.293a1 1 0 001.414-1.414l-7-7z" />
                  </svg>
                  <span class="sr-only">Home</span>
                <% end %>
              </div>
            </li>

            <li>
              <div class="flex items-center">
                <svg class="flex-shrink-0 h-5 w-5 text-gray-300" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20" aria-hidden="true">
                  <path d="M5.555 17.776l8-16 .894.448-8 16-.894-.448z" />
                </svg>
                <%= link_to t('.videos'), videos_list_path, class: "ml-4 text-sm font-medium text-gray-500 hover:text-gray-700" %>
              </div>
            </li>

            <li>
              <div class="flex items-center">
                <svg class="flex-shrink-0 h-5 w-5 text-gray-300" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20" aria-hidden="true">
                  <path d="M5.555 17.776l8-16 .894.448-8 16-.894-.448z" />
                </svg>
                <span class="ml-4 text-sm font-medium text-gray-500"><%= t('.new_video') %></span>
              </div>
            </li>

          </ol>
        </div>
      </nav>
    </div>
  </div>


  <main class="py-6 bg-gray-100 h-screen">
    <div class="max-w-3xl mx-auto px-4 sm:px-6 md:px-8">
      <h1 class="font-bold text-2xl"><%= t('.new_video') %></h1>
      <%= render "form", video: @video %>
    </div>
  </main>
</div>

app/views/videos/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @video %>

    <%= link_to 'Edit this video', edit_video_path(@video), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this video', video_path(@video), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to videos', videos_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>

    <%= turbo_stream_from :video_comments %>
    <%= turbo_frame_tag "comments_module", src: video_comments_path(id: params[:id]) %>
  </div>
</div>


<ul role="list" class="grid grid-cols-1 gap-4 sm:gap-6 sm:grid-cols-2 xl:grid-cols-4 mt-3">
  <li class="relative col-span-1 flex shadow-sm rounded-md">
    <div class="flex-shrink-0 flex items-center justify-center w-16 bg-pink-600 text-white text-sm font-medium rounded-l-md">
      GA
    </div>
    <div class="flex-1 flex items-center justify-between border-t border-r border-b border-gray-200 bg-white rounded-r-md truncate">
      <div class="flex-1 px-4 py-2 text-sm truncate">
        <a href="#" class="text-gray-900 font-medium hover:text-gray-600">
          GraphQL API
        </a>
        <p class="text-gray-500">12 Members</p>
      </div>
      <div class="flex-shrink-0 pr-2">
        <button type="button" class="w-8 h-8 bg-white inline-flex items-center justify-center text-gray-400 rounded-full hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-purple-500" id="pinned-project-options-menu-0-button" aria-expanded="false" aria-haspopup="true">
          <span class="sr-only">Open options</span>
          <!-- Heroicon name: solid/dots-vertical -->
          <svg class="w-5 h-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
            <path d="M10 6a2 2 0 110-4 2 2 0 010 4zM10 12a2 2 0 110-4 2 2 0 010 4zM10 18a2 2 0 110-4 2 2 0 010 4z" />
          </svg>
        </button>

        <!--
          Dropdown menu, show/hide based on menu state.

          Entering: "transition ease-out duration-100"
            From: "transform opacity-0 scale-95"
            To: "transform opacity-100 scale-100"
          Leaving: "transition ease-in duration-75"
            From: "transform opacity-100 scale-100"
            To: "transform opacity-0 scale-95"
        -->
        <div class="z-10 mx-3 origin-top-right absolute right-10 top-3 w-48 mt-1 rounded-md shadow-lg bg-white ring-1 ring-black ring-opacity-5 divide-y divide-gray-200 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="pinned-project-options-menu-0-button" tabindex="-1">
          <div class="py-1" role="none">
            <!-- Active: "bg-gray-100 text-gray-900", Not Active: "text-gray-700" -->
            <a href="#" class="text-gray-700 block px-4 py-2 text-sm" role="menuitem" tabindex="-1" id="pinned-project-options-menu-0-item-0">View</a>
          </div>
          <div class="py-1" role="none">
            <a href="#" class="text-gray-700 block px-4 py-2 text-sm" role="menuitem" tabindex="-1" id="pinned-project-options-menu-0-item-1">Removed from pinned</a>
            <a href="#" class="text-gray-700 block px-4 py-2 text-sm" role="menuitem" tabindex="-1" id="pinned-project-options-menu-0-item-2">Share</a>
          </div>
        </div>
      </div>
    </div>
  </li>

  <!-- More items... -->
</ul>