config/routes.rb
Rails.application.routes.draw do
  resources :pages
  get 'channel/:channel_id/library', to: 'channels#library', as: :library
  resources :library_items
  resources :library_folders
  get 'course_items/category'
  resources :course_items
  resources :question_comments do
    resource :question_comment_votes, only: :show
  end
  resources :questions
  resources :lesson_comments
  resources :lessons
  resources :community_comments do
    resource :community_comment_votes, only: :show
  end
  resources :article_comments do
    resource :article_comment_votes, only: :show
  end
  resources :video_comments do
    resource :video_comment_votes, only: :show
  end
  get 'dashboard/index'
  get 'communities/list'
  resources :communities
  get 'courses/info'
  get 'courses/list'
  resources :courses
  resources :webhooks, only: [:create]
  get 'articles/list'
  resources :articles
  get 'videos/list'
  resources :videos
  resources :channels
  get 'account_affiliations/info'
  get 'account_affiliations/become_admin'
  resources :account_affiliations
  get 'accounts/switch'
  get 'accounts/select'
  get 'accounts/manage'
  get 'accounts/user_info'
  get 'accounts/new_affiliation'
  get 'accounts/members'
  get 'accounts/confirmed'
  get 'accounts/:id/configuration', to: 'accounts#configuration', as: :account_configuration
  resources :accounts do
    collection do
      post :search
    end
  end
  devise_for :users
  get 'home/index'
  root to: "home#index"
end

app/models/course_item.rb
class CourseItem < ApplicationRecord
  include ActionView::RecordIdentifier
  belongs_to :course
  acts_as_list scope: :course

  enum category: [:section, :lesson, :quizz]

  after_create_commit do
    course = Course.find(self.course_id)
    broadcast_append_to :course_items, target: "existing_items_#{dom_id(course)}", partial: "course_items/course_item", locals: { course_item: self }
  end
end

app/controllers/course_items_controller.rb
class CourseItemsController < ApplicationController
  
  def index
    @course = Course.friendly.find(params[:id])
    puts @course.title
    @course_items = @course.course_items
  end

  def show
    @course_item = CourseItem.find(params[:id])
  end

  def new
    @course_item = CourseItem.new
    @course = Course.find(params[:course_id])
    @category = params[:category]
  end

  def edit
    @course_item = CourseItem.find(params[:id])
    @course = @course_item.course_id
  end

  def create
    @course_item = CourseItem.new(course_item_params)
    @course = Course.find(@course_item.course_id)
    
    respond_to do |format|
      if @course_item.save
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @community_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @course_item = GlobalID::Locator.locate_signed(params[:sgid])
    @course_item.insert_at(params[:position])
  end

  def category
    @course = Course.find(params[:course_id])
  end

  private
    def course_item_params
      params.require(:course_item).permit(:user_id, :course_id, :name, :category, :position)
    end
end

app/views/course_items/_category.html.erb
<%= turbo_frame_tag "new_course_item" do %>
  <div class="flex mt-4">
    <%= link_to "New section", new_course_item_path(course_id: @course.id, category: 'section'), class: "bg-blue-600 px-4 py-2 text-white rounded mx-2" %>
    <%= link_to "New lesson", new_course_item_path(course_id: @course.id, category: 'lesson'), class: "bg-blue-600 px-4 py-2 text-white rounded mx-2" %>
    <%= link_to "New quizz", new_course_item_path(course_id: @course.id, category: 'quizz'), class: "bg-blue-600 px-4 py-2 text-white rounded mx-2" %>
  </div>
<% end %>

app/views/course_items/_course_item.html.erb
<% if course_item.category == "lesson" %>
  <%= content_tag :div, id: dom_id(course_item), data: { sgid: course_item.to_sgid_param }, class: "bg-gray-100 px-4 py-1 my-1 border" do %>
    <div class="relative flex">
      <div> 
        <%= course_item.name %> <span class="text-sm text-gray-600">- lesson</span>
      </div>
      <div class="absolute right-0 mr-2">
        <%= link_to t('.edit'), edit_course_item_path(course_item), target: '_top' %>
      </div>
    </div>
  <% end %>
<% elsif course_item.category == "section" %>
  <%= content_tag :div, id: dom_id(course_item), data: { sgid: course_item.to_sgid_param }, class: "bg-gray-300 px-2 py-1 my-1 border font-bold" do %>
    <%= course_item.name %> <span class="text-sm text-gray-600">- section</span>
  <% end %>
<% elsif course_item.category == "quizz" %>
  <%= content_tag :div, id: dom_id(course_item), data: { sgid: course_item.to_sgid_param }, class: "bg-gray-100 px-4 py-1 my-1 border" do %>
    <%= course_item.name %>  <span class="text-sm text-gray-600">- quizz</span>
  <% end %>
<% end %>

app/views/course_items/_form.html.erb
<%= turbo_frame_tag "new_course_item", target: :_top do %>
  <%= form_with(model: course_item, class: "contents") do |form| %>
    
    <%= form.hidden_field :course_id, value: course_id %>
    <%= form.hidden_field :category, value: category %>

    <h3><%= category %></h3>
    <div class="my-5">
      <%= form.label :name %>
      <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", autofocus: true %>
    </div>

    <div class="inline">
      <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
    </div>
  <% end %>
<% end %>

app/views/course_items/create.turbo_stream.erb
<%= turbo_stream.replace "new_course_item", partial: "course_items/category", locals: { course_id: @course.id } %>

app/views/course_items/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing lesson</h1>

  <%= render "form", course_item: @course_item, course_id: @course %>

  <%= link_to "Show this lesson", @course_item, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to course", course_path(@course_item.course_id), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/course_items/index.html.erb
<%= render ("layouts/dashboard") %>
  
  <div class="max-w-7xl mx-auto px-4 sm:px-6">
    <div class="border-t border-gray-200 py-3">
      <nav class="flex" aria-label="Breadcrumb">
        
        <div class="hidden sm:block">
          <ol role="list" class="flex items-center space-x-4">
            <li>
              <div>
                <%= link_to dashboard_index_path, class: "text-gray-400 hover:text-gray-500" do %>
                  <svg class="flex-shrink-0 h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                    <path d="M10.707 2.293a1 1 0 00-1.414 0l-7 7a1 1 0 001.414 1.414L4 10.414V17a1 1 0 001 1h2a1 1 0 001-1v-2a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 001 1h2a1 1 0 001-1v-6.586l.293.293a1 1 0 001.414-1.414l-7-7z" />
                  </svg>
                  <span class="sr-only">Home</span>
                <% end %>
              </div>
            </li>

            <li>
              <div class="flex items-center">
                <svg class="flex-shrink-0 h-5 w-5 text-gray-300" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20" aria-hidden="true">
                  <path d="M5.555 17.776l8-16 .894.448-8 16-.894-.448z" />
                </svg>
                <%= link_to t('.courses'), courses_list_path, class: "ml-4 text-sm font-medium text-gray-500 hover:text-gray-700" %>
              </div>
            </li>

            <li>
              <div class="flex items-center max-w-xs">
                <svg class="flex-shrink-0 h-5 w-5 text-gray-300" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20" aria-hidden="true">
                  <path d="M5.555 17.776l8-16 .894.448-8 16-.894-.448z" />
                </svg>
                <%= link_to @course.title, courses_info_path(id: @course.id), class: "ml-4 text-sm font-medium text-gray-500 truncate" %>
              </div>
            </li>

            <li>
              <div class="flex items-center">
                <svg class="flex-shrink-0 h-5 w-5 text-gray-300" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20" aria-hidden="true">
                  <path d="M5.555 17.776l8-16 .894.448-8 16-.894-.448z" />
                </svg>
                <span class="ml-4 text-sm font-medium text-gray-500"><%= t('.course_contents') %></span>
              </div>
            </li>

          </ol>
        </div>
      </nav>
    </div>
  </div>

  <main class="py-6 bg-gray-100 h-screen">
    <div class="max-w-3xl mx-auto sm:px-6 lg:max-w-5xl">
      <div class="flex items-center space-x-5">
        <div>
          <h1 class="font-bold text-2xl"><%= t('.course_contents') %></h1>
        </div>
      </div>
    </div>
    <div class="mt-6 max-w-3xl mx-auto gap-6 sm:px-6 lg:max-w-5xl">
      <div class="bg-white shadow sm:rounded-lg sm:overflow-hidden px-4 py-5 sm:px-6 mb-8">
        <h2 class="font-bold text-xl mb-8"><%= @course.title %></h2>
        <%= turbo_stream_from :course_items %>
        <%= turbo_frame_tag "items_#{dom_id(@course)}" do %>
          <div data-controller="position" id=<%= %"existing_items_#{dom_id(@course)}"%>>
            <%= render @course_items %>
          </div>
        <% end %>
        
        <%= render "category" %>
        
      </div>
    </div>
  </main>
</div>

app/views/course_items/new.html.erb
NEW
<%= turbo_frame_tag "new_course_item" do %>
  <%= render "form", course_item: @course_item, course_id: params[:course_id], category: params[:category] %>
<% end %>